package vista;

import almacen.Almacen;
import dataBase.MetodosSQL;

public class IntFrm extends javax.swing.JInternalFrame {

    protected Almacen almacen;
    protected MetodosSQL mSQL;
    
    /**
     * Creates new form IntFrm
     */

    public IntFrm(Almacen almacen, MetodosSQL mSQL) {
        initComponents();
        this.almacen = almacen;
        this.mSQL = mSQL;
    }

    public Almacen getAlmacen() {
        return this.almacen;
    }

    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }

    public MetodosSQL getmSQL() {
        return this.mSQL;
    }

    public void setmSQL(MetodosSQL mSQL) {
        this.mSQL = mSQL;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
